esphome:
  name: cuina
  friendly_name: cuina

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Allow web connection with the device
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "hvu1+maMxVb0/R/XXg8hUMqikwuSFYhbgyAC45LR64k="

ota:
  - platform: esphome
    password: "8633b78f11f063f0212ea71fbff6011e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cuina Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# https://esphome.io/components/light/neopixelbus.html

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO02  # pin D4
    num_leds: 5
    name: "Llum NeoPixel"

# port i2c
i2c:
  sda: GPIO04
  scl: GPIO05
  scan: true
  id: bus_a
#  frequency: 200khz

sensor:
  # https://esphome.io/components/sensor/ens160.html
  # https://community.home-assistant.io/t/temperature-problem-with-an-ens160-aht21/681013
  # ENS160 qualitat aire, co2 i voc
  - platform: ens160_i2c
    eco2:
      name: "ENS160 eCO2"
    tvoc:
      name: "ENS160 VOC" # Total Volatile Organic Compounds
    aqi:
      id: id_ENS160_air_quality_index
      name: "ENS160 Air Quality Index"
    update_interval: 10s
    address: 0x53
    compensation:
      temperature: id_AHT21_temp
      humidity: id_AHT21_hum

  # AHT21 temperatura i humitat
  - platform: aht10
    variant: AHT20
    temperature:
      name: "AHT21 Temp"
      id: id_AHT21_temp
    humidity:
      name: "AHT21 Humitat"
      id: id_AHT21_hum
    update_interval: 10s  
    address: 0x38

  # https://esphome.io/components/sensor/ina219.html
  # INA219 sensor corrent DC
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "INA219 Corrent"
    power:
      name: "INA219 Potència"
    bus_voltage:
      name: "INA219 Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 5s
