esphome:
  name: garatge
  friendly_name: garatge

esp8266:
  board: d1_mini

# Enable logging
logger:

# Allow web connection with the device
web_server:
  port: 80

ota:
  - platform: esphome
    password: "8b4e4769cf8e5dcd5eb2b678f4d3aedf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal)
  # if wifi connection fails
  ap:
    ssid: "garatge Fallback Hotspot"
    password: !secret wifi_password

  # Optional manual IP. Needed if the mDNS does not work
  # and garatge.local is not found
  #manual_ip:
  #  static_ip: 192.168.31.22
  #  gateway: 192.168.31.1
  #  subnet: 255.255.255.0

captive_portal:

# https://esphome.io/guides/automations
# https://siytek.com/esphome-servo-example/

# Enable Home Assistant API
# to receive data from Home Assistant
api:
  #encryption:
  #  key: "0PkU57hxRz+KYkiuGvCZjBL2CUmYtKVj9WXKT6Daf4s="
  services:
    - service: control_servo
      variables:
        level: float
  # Home Assistant will create a custom service named
  # esphome.garatge_control_servo
  # and the data will be passed to the variable level
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return level / 100.0;'
  # and write the value level to the servo component

# An output component tells ESPHome to send data to our servo
output:
  - platform: esp8266_pwm    # our servo requires a PWM signal
    id: pwm_output    # to receive the data
    pin: GPIO14    # Wemos pin D5
    frequency: 50 Hz
  - platform: gpio
    id: bd_led
    pin: GPIO02     # Wemos pin D4
    inverted: true

# The servo component will act as the link between
# the output component and 
# the incoming data from Home Assistant
servo:
  - id: my_servo    # will receive the data from Home Assistant
    output: pwm_output    # to pass the data to the output
    # transition_length: 1s    # time needed for a full movement

# https://esphome.io/components/light/binary.html?highlight=light

light:
  - platform: binary
    output: bd_led
    name: "Builtin LED wemos"

# https://esphome.io/components/binary_sensor/gpio.html

binary_sensor:
  - platform: gpio
    pin: GPIO12  # Wemos pin D6
    name: "Sensor Tall Porta Garatge"
