esphome:
  name: llum
  friendly_name: llum

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Allow web connection with the device
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "SaclHGDarPHaPAMXWtCsWQ1YF7qwBhnxFyKYiuLXgNU="
    # key: "7k5QvDw26ZFR275TIE4gYsBgYsIUsyOtRieS5xsIdsk="

ota:
  - platform: esphome
    password: "96851e17b759666cb95e9c8942eb93f3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Llum Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# https://esphome.io/components/switch/gpio.html

switch:
  - platform: gpio
    pin: GPIO00
    name: "Llum habitacio"
    inverted: true
