esphome:
  name: ventilador
  friendly_name: ventilador

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Allow web connection with the device
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "a0WsUkHKCa1bfVLCp3jL0zX4EDuG1z5qDsJAMIl9f30="

ota:
  - platform: esphome
    password: "091f4a92da716d6c15952fe499cd7783"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ventilador Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

# https://esphome.io/components/switch/gpio.html

switch:
  - platform: gpio
    pin: GPIO00
    name: "Extractor WC"
    inverted: true
