- id: 744196297eef4484ab72e89d5845875e
  alias: Write Servo Value to ESP
  trigger:
    platform: state
    entity_id: input_number.servo_control
  action:
  - service: esphome.garatge_control_servo
    data_template:
      level: '{{ trigger.to_state.state | int }}'

- id: ffa51196fbf641f59374dd9a9e8db4e0
  alias: Envia Obre Porta
  triggers:
  - entity_id: input_button.obre_porta
    trigger: state
  actions:
  - data_template:
      level: '{{ 50 | int }}'
    enabled: false
    action: esphome.garatge_control_servo
  - data:
      level: 50
    enabled: false
    action: esphome.garatge_control_servo
  - data:
      value: 50
    target:
      entity_id: input_number.servo_control
    enabled: false
    action: input_number.set_value
  - target:
      entity_id: input_boolean.obrint_tancant
    action: input_boolean.turn_on
    data: {}
  - repeat:
      while:
      - condition: numeric_state
        entity_id: input_number.servo_control
        below: 50
      - condition: state
        entity_id: input_boolean.obrint_tancant
        state: 'on'
        enabled: true
      sequence:
      - data:
          value: '{{states(''input_number.servo_control'') | int + 1}}'
        target:
          entity_id: input_number.servo_control
        action: input_number.set_value
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 20

- id: ce9c2c38f43445e299d7e4248d2d1ba7
  alias: Envia Tanca Porta
  triggers:
  - entity_id: input_button.tanca_porta
    trigger: state
  actions:
  - target:
      entity_id: input_boolean.obrint_tancant
    action: input_boolean.turn_off
    data: {}
  - repeat:
      while:
      - condition: or
        conditions:
        - condition: and
          conditions:
          - condition: state
            entity_id: binary_sensor.garatge_sensor_tall_porta_garatge
            state: 'on'
          - condition: numeric_state
            entity_id: input_number.servo_control
            above: -60
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: input_number.servo_control
            above: -100
          - condition: numeric_state
            entity_id: input_number.servo_control
            below: -59
      - condition: state
        entity_id: input_boolean.obrint_tancant
        state: 'off'
      sequence:
      - data:
          value: '{{states(''input_number.servo_control'') | int - 1}}'
        target:
          entity_id: input_number.servo_control
        action: input_number.set_value
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 20

- id: '1681559791091'
  alias: Led wemos Encen
  description: Si slider >45 encen led wemos
  trigger:
  - platform: state
    entity_id:
    - input_number.servo_control
  condition:
  - condition: numeric_state
    entity_id: input_number.servo_control
    above: 45
  action:
  - alias: Encendre onboard LED wemos garatge
    type: turn_on
    device_id: e2c2b4738ce3ca7517162a6fa8daecbd
    entity_id: light.garatge_builtin_led_wemos
    domain: light
  mode: single

- id: '1681833368706'
  alias: Led wemos Apaga
  description: Si slider <-95 apaga led wemos
  trigger:
  - platform: state
    entity_id:
    - input_number.servo_control
  condition:
  - condition: numeric_state
    entity_id: input_number.servo_control
    below: -95
  action:
  - type: turn_off
    device_id: e2c2b4738ce3ca7517162a6fa8daecbd
    entity_id: light.garatge_builtin_led_wemos
    domain: light
  mode: single

- id: '1708019826120'
  alias: Obre porta garatge si sensor tall activat
  description: A l'activar-se el sensor de tall de la porta del garatge força a que
    s'obri de nou
  trigger:
  - type: turned_off
    platform: device
    device_id: e2c2b4738ce3ca7517162a6fa8daecbd
    entity_id: binary_sensor.garatge_sensor_tall_porta_garatge
    domain: binary_sensor
  condition:
  - condition: numeric_state
    entity_id: input_number.servo_control
    above: -60
  action:
  - service: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.envia_obre_porta
  mode: single

- id: '1708451147633'
  alias: Humitat WC Activa ventilador
  description: Humitat WC > 80% activa l'extractor
  triggers:
  - entity_id:
    - sensor.bany_wc_humitat
    above: 80
    trigger: numeric_state
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.ventilador_extractor_wc
    action: switch.turn_on
  mode: single

- id: '1708451244474'
  alias: Humitat WC Atura ventilador
  description: Humitat WC < 60% atura l'extractor
  triggers:
  - entity_id:
    - sensor.bany_wc_humitat
    below: 60
    trigger: numeric_state
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: switch.ventilador_extractor_wc
    action: switch.turn_off
  mode: single

- id: dbf6a32eb2fe42778c0fe22857df97a9
  alias: Alerta de Fum llum cuina en vermell
  description: Pampalluga llum cuina en vermell quan hi ha alerta de fum
  trigger:
  - type: humidity
    platform: device
    device_id: 5fc4969d50e0b877ab8f5f087f427e7f
    entity_id: 6a986054991e4f0b43fbf16ef1b222fe
    domain: sensor
    above: 60
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id:
      - input_boolean.polsador_alerta
    data: {}
  - repeat:
      while:
      - condition: state
        entity_id: input_boolean.polsador_alerta
        state: 'on'
      sequence:
      - service: light.turn_on
        data:
          rgb_color:
          - 255
          - 0
          - 0
          transition: 0
        enabled: true
        target:
          entity_id: light.cuina_llum_neopixel
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - if:
        - condition: state
          entity_id: input_boolean.polsador_tiraled
          state: 'off'
        then:
        - service: light.turn_off
          data:
            transition: 0
          target:
            entity_id: light.cuina_llum_neopixel
        else:
        - service: light.turn_on
          data:
            rgb_color:
            - 255
            - 255
            - 255
            transition: 0
          target:
            entity_id: light.cuina_llum_neopixel
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500

- id: '1710441133017'
  alias: Alertes Fum i Rentadora Atureu-vos
  description: Desactiva el boolean Polsador Alerta al prèmer botó Apaga Alertes
  trigger:
  - platform: state
    entity_id:
    - input_button.apaga_alertes
  condition: []
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.polsador_alerta
    data: {}
  mode: single

- id: '1734522509427'
  alias: Timbre polsat sona
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.entrada_timbre_porta
  condition: []
  action:
  - service: esphome.entrada_play_rtttl
    data:
      song_str: scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b
  mode: single

- id: '1734695682093'
  alias: S'escanegi l'etiqueta Nfc amb mòbil Carles
  description: Encén llum cuina en groc
  trigger:
  - platform: tag
    tag_id: 8244e60b-82fd-48f3-ba4d-88bc5b773d3b
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 255
      - 255
      - 0
    target:
      device_id: 5fc4969d50e0b877ab8f5f087f427e7f
  mode: single

- id: '1734696239864'
  alias: Pany Targeta blanca sona missionimpossible
  description: Ha arribat la targeta blanca
  trigger:
  - platform: tag
    tag_id: 43-60-11-94
  condition: []
  action:
  - service: esphome.entrada_play_rtttl
    data:
      song_str: mission_imp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d
  mode: single

- id: '1734696464189'
  alias: Pany Tag blau sona starwars
  description: Ha arribat el tag blau
  trigger:
  - platform: tag
    tag_id: D3-4D-2F-1C
  condition: []
  action:
  - service: esphome.entrada_play_rtttl
    data:
      song_str: star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p
  mode: single

- id: '1738088350604'
  alias: Timbre polsat llum cuina en blau
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.entrada_timbre_porta
  condition: []
  action:
  - repeat:
      count: 5
      sequence:
      - service: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 77
          - 189
          - 245
          transition: 0
        target:
          entity_id: light.cuina_llum_neopixel
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - if:
        - condition: state
          entity_id: input_boolean.polsador_tiraled
          state: 'off'
        then:
        - service: light.turn_off
          data:
            transition: 0
          target:
            entity_id: light.cuina_llum_neopixel
        else:
        - service: light.turn_on
          data:
            rgb_color:
            - 255
            - 255
            - 255
            transition: 0
          target:
            entity_id: light.cuina_llum_neopixel
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
  mode: single

- id: '1739895376813'
  alias: Llum cuina Encen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.polsador_tiraled
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 255
      - 255
      - 255
      transition: 0
    target:
      entity_id: light.cuina_llum_neopixel
  mode: single

- id: '1739895437533'
  alias: Llum cuina Apaga
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.polsador_tiraled
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.cuina_llum_neopixel
    data:
      transition: 0
  mode: single

- id: '1739895616746'
  alias: Alerta Rentadora acabada llum cuina en verd
  description: Pampalluga llum cuina en vermell quan hi ha alerta de fum
  triggers:
  - type: current
    device_id: 5fc4969d50e0b877ab8f5f087f427e7f
    entity_id: d586a4793d32e05e175d3195e0fa6095
    domain: sensor
    below: 0.001
    trigger: device
  conditions: []
  actions:
  - target:
      entity_id:
      - input_boolean.polsador_alerta
    data: {}
    action: input_boolean.turn_on
  - repeat:
      while:
      - condition: state
        entity_id: input_boolean.polsador_alerta
        state: 'on'
      sequence:
      - data:
          rgb_color:
          - 0
          - 255
          - 0
          transition: 0
        enabled: true
        target:
          entity_id: light.cuina_llum_neopixel
        action: light.turn_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - if:
        - condition: state
          entity_id: input_boolean.polsador_tiraled
          state: 'off'
        then:
        - data:
            transition: 0
          target:
            entity_id: light.cuina_llum_neopixel
          action: light.turn_off
        else:
        - data:
            rgb_color:
            - 255
            - 255
            - 255
            transition: 0
          target:
            entity_id: light.cuina_llum_neopixel
          action: light.turn_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 0
          milliseconds: 500
  mode: single

- id: '1740674691145'
  alias: Llum entrada Encen amb Pir
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.entrada_pir_sensor
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.entrada_llum_entrada
  mode: single

- id: '1740674720028'
  alias: Llum entrada Apaga amb Pir
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.entrada_pir_sensor
    from: 'on'
    to: 'off'
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.entrada_llum_entrada
  mode: single
